### PR TITLE
Add mix formatter

### PR DESCRIPTION
**Pull request by flowerett**
Autoformatting is a common practice for all OS projects, let's add it @nurugger07

### CODE REVIEW

**Comment by nurugger07** [comment]
@flowerett can you please resolve and then I'll get it merged? Thanks for contributing!

**Comment by flowerett** [comment]
@nurugger07 done!

**Comment by fenollp** [comment]
Can we merge this?

**Comment by nurugger07** [comment]
@flowerett thanks!

**Pull request merged**
